Animebase/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from anime.views import AnimeListView
from .views import login_page, register_page, logout_view, emailView, successView
from .sitemaps import StaticViewSitemap, AnimeSitemap, EpisodeSiteMap, AnimeGenreMap

sitemaps = {
    'static': StaticViewSitemap,
    'anime': AnimeSitemap,
    'episode': EpisodeSiteMap,
    'genre': AnimeGenreMap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', AnimeListView.as_view(), name='list'),
    path('login/', login_page, name='login'),
    path('register/', register_page, name='register'),
    path('logout/', logout_view, name='logout'),
    path('contact/', emailView, name='contact'),
    path('contact/success/', successView, name='success'),
    path('sitemap.xml/', sitemap, { 'sitemaps': sitemaps }, name='django.contrib.sitemaps.views.sitemap'),
    path('anime/', include('anime.urls', namespace='anime')),
    path('jet/', include('jet.urls', namespace='jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', namespace='jet-dashboard')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

anime/urls.py
from django.urls import path

from anime.views import AnimeListView, AnimeDetailView, EpisodeDetailView, LatestAnimeView, DirectoryAnimeView, \
    HotAnimeView, autocomplete

app_name = 'anime'

urlpatterns = [
    path('', AnimeListView.as_view(), name='list'),
    path('search/', autocomplete, name='search'),
    path('latest/', LatestAnimeView.as_view(), name='latest'),
    path('hot/', HotAnimeView.as_view(), name='hot'),
    path('directory/<cat>/', DirectoryAnimeView.as_view(), name='directory'),
    path('<slug>/', AnimeDetailView.as_view(), name='detail'),
    path('<anime>/<episode>/', EpisodeDetailView.as_view(), name='episode_detail'),
]

templates/snippets/footer.html
{# <!-- Footer -->
<footer class="page-footer font-small dark pt-5 mt-5">

    <!-- Footer Links -->
    <div class="container text-center text-md-left">

        <!-- Grid row -->
        <div class="row">

            <!-- Grid column -->
            <div class="col-md-6 mt-md-0 mt-3">

                <!-- Content -->
                <h5 class="text-uppercase">Animebase</h5>
                <p>Animebase - Watch your favorite Anime for free online in high quality.KissAnime Free download high quality from 480p to 1080p </p>

            </div>
            <!-- Grid column -->

            <hr class="clearfix w-100 d-md-none pb-3">

            <!-- Grid column -->
            <div class="col-md-3 mb-md-0 mb-3">

                <!-- Links -->
                <h5 class="text-uppercase">Navigation</h5>

                <ul class="list-unstyled">
                    <li><a href="{% url 'anime:list' %}">Home</a></li>
                    <li><a href="{% url 'anime:latest' %}">Latest</a></li>
                    <li><a href="{% url 'anime:directory' cat='Romance' %}">Directory</a></li>
                    <li><a href="#">Random Anime</a></li>
                </ul>

            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-3 mb-md-0 mb-3">

                <!-- Links -->
                <h5 class="text-uppercase">Services</h5>

                <ul class="list-unstyled">
                    <li><a href="#">About Us</a></li>
                    <li><a href="{% url 'contact' %}">Contact Us</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                    <li><a href="#">DMCA</a></li>
                </ul>

            </div>
            <!-- Grid column -->

        </div>
        <!-- Grid row -->

    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3 dark-footer">© 2018 Copyright:
        <a href="#" class="gold_link"> Animebase.in</a> | All Rights Reserved
    </div>
    <!-- Copyright -->

</footer>
<!-- Footer --> #}

templates/snippets/navbar.html
{# {% url 'anime:hot' as hot_url %}
{% url 'anime:list' as list_url %}
{% url 'anime:latest' as latest_url %}
{% url 'anime:directory' cat='Romance' as directory_url %}

<nav class="navbar navbar-expand-lg navbar-dark mb-3" style="background-color: #0c0c0c;">
    <div class="container">
        <a class="navbar-brand" href="{% url 'list' %}">ANIMEBASE</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.path == list_url %} active {% endif %}">
                    <a class="item-link nav-link" href="{% url 'list' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item {% if request.path == latest_url %} active {% endif %}">
                    <a class="nav-link" href="{% url 'anime:latest' %}">Latest</a>
                </li>
                <li class="nav-item {% if request.path == hot_url %} active {% endif %}">
                    <a class="nav-link" href="{% url 'anime:hot' %}">Hot</a>
                </li>
                <li class="nav-item {% if request.path == directory_url %} active {% endif %}">
                    <a class="nav-link" href="{% url 'anime:directory' cat='Romance' %}">Directory</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-user-circle fa-lg" aria-hidden="true"></i>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color: #212121;">
                        {% if request.user.is_authenticated %}
                            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                        {% else %}
                            <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                            <a class="dropdown-item" href="{% url 'login' %}">Register</a>
                        {% endif %}
                    </div>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" method="get">
                <input class="form-control mr-sm-2" type="search" placeholder="Search"
                       aria-label="Search" id="id-input" name="q">
                <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav> #}